const htmlContentTypes = ["text/html", "application/xhtml+xml"];

function source(input) {
  return Object.freeze({
    verified: true,
    enabled: true,
    cadenceHours: 12,
    checkedAt: "2026-09-14",
    sourceDocumentType: "Notice",
    acceptedContentTypes: htmlContentTypes,
    ...input,
    allowedHosts: Object.freeze([...input.allowedHosts]),
    acceptedContentTypes: Object.freeze([...(input.acceptedContentTypes || htmlContentTypes)]),
  });
}

export const defaultNewsSources = Object.freeze([
  source({
    id: "federal-register",
    publisher: "Federal Register",
    adapter: "federal-register",
    url: "https://www.federalregister.gov/api/v1/documents.json",
    allowedHosts: ["www.federalregister.gov", "www.govinfo.gov"],
    acceptedContentTypes: ["application/json"],
    cadenceHours: 6,
    agencies: [
      "homeland-security-department",
      "u-s-citizenship-and-immigration-services",
      "u-s-immigration-and-customs-enforcement",
      "u-s-customs-and-border-protection",
      "state-department",
      "education-department",
      "labor-department",
      "treasury-department",
      "internal-revenue-service",
      "social-security-administration",
      "executive-office-of-the-president",
    ],
  }),
  source({
    id: "uscis",
    publisher: "U.S. Citizenship and Immigration Services",
    adapter: "index-page",
    url: "https://www.uscis.gov/newsroom/all-news",
    allowedHosts: ["www.uscis.gov"],
    itemSelector: "main .view-content > .views-row",
  }),
  source({
    id: "ice-sevp",
    publisher: "Student and Exchange Visitor Program",
    adapter: "index-page",
    url: "https://www.ice.gov/sevis/whats-new",
    allowedHosts: ["www.ice.gov", "www.federalregister.gov", "studyinthestates.dhs.gov"],
    itemSelector: "main .usa-card-group > .usa-card",
  }),
  source({
    id: "study-in-the-states",
    publisher: "Study in the States",
    adapter: "index-page",
    url: "https://studyinthestates.dhs.gov/",
    allowedHosts: ["studyinthestates.dhs.gov"],
    enabled: false,
    pendingReason: "The former /news endpoint returned 404 on 2026-09-14; no bounded replacement listing is verified.",
  }),
  source({
    id: "state-visa-news",
    publisher: "U.S. Department of State",
    adapter: "index-page",
    url: "https://travel.state.gov/content/travel/en/News/visas-news.html",
    allowedHosts: ["travel.state.gov"],
    enabled: false,
    pendingReason: "The official page denied automated retrieval on 2026-09-14; selector contract is pending.",
  }),
  source({
    id: "state-travel-rss",
    publisher: "U.S. Department of State",
    adapter: "feed",
    url: "https://travel.state.gov/_res/rss/TAsTWs.xml",
    allowedHosts: ["travel.state.gov"],
    acceptedContentTypes: ["application/rss+xml", "application/xml", "text/xml"],
    enabled: false,
    pendingReason: "The feed covers broad travel advisories rather than student-visa updates; relevance contract is pending.",
  }),
  source({
    id: "cbp",
    publisher: "U.S. Customs and Border Protection",
    adapter: "index-page",
    url: "https://www.cbp.gov/newsroom/media-releases/all?combine=&field_date_release_value=All&field_newsroom_type_target_id_1=81",
    allowedHosts: ["www.cbp.gov"],
    itemSelector: "main .view-content .usa-collection__item",
  }),
  source({
    id: "irs",
    publisher: "Internal Revenue Service",
    adapter: "index-page",
    url: "https://www.irs.gov/newsroom",
    allowedHosts: ["www.irs.gov"],
    enabled: false,
    pendingReason: "A bounded student-relevant listing contract has not been verified.",
  }),
  source({
    id: "ssa",
    publisher: "Social Security Administration",
    adapter: "index-page",
    url: "https://www.ssa.gov/news/en/press/releases/",
    allowedHosts: ["www.ssa.gov"],
    enabled: false,
    pendingReason: "A bounded student-relevant listing contract has not been verified.",
  }),
  source({
    id: "labor",
    publisher: "U.S. Department of Labor",
    adapter: "index-page",
    url: "https://www.dol.gov/newsroom/releases",
    allowedHosts: ["www.dol.gov"],
    enabled: false,
    pendingReason: "A bounded student-relevant listing contract has not been verified.",
  }),
  source({
    id: "white-house",
    publisher: "The White House",
    adapter: "index-page",
    url: "https://www.whitehouse.gov/presidential-actions/",
    allowedHosts: ["www.whitehouse.gov"],
    cadenceHours: 6,
    sourceDocumentType: "Presidential Action",
    enabled: false,
    pendingReason: "A stable bounded presidential-action selector contract has not been verified.",
  }),
]);

export function defaultNewsSource(sourceId) {
  return defaultNewsSources.find(({ id }) => id === sourceId) || null;
}
